export const ELEVENLABS_CONFIG = {
  voiceId: "21m00Tcm4TlvDq8ikWAM", // Rachel - default female voice
  model: "eleven_multilingual_v2",
  outputFormat: "mp3_44100_128",
};

export const ELEVENLABS_VOICES = {
  rachel: "21m00Tcm4TlvDq8ikWAM",
  drew: "29vD33N1CtxCmqQRPOHJ",
  clyde: "2EiwWnXFnvU5JabPnv8n",
  paul: "5Q0t7uMcjvnagumLfvZi",
  domi: "AZnzlk1XvdvUeBnXmlld",
  dave: "CYw3kZ02Hs0563khs1Fj",
  fin: "D38z5RcWu1voky8WS1ja",
  sarah: "EXAVITQu4vr4xnSDxMaL",
  antoni: "ErXwobaYiN019PkySvjV",
  thomas: "GBv7mTt0atIp3Br8iCZE",
  charlie: "IKne3meq5aSn9XLyUdCD",
  emily: "LcfcDJNUP1GQjkzn1xUU",
  elli: "MF3mGyEYCl7XYWbV9V6O",
  callum: "N2lVS1w4EtoT3dr4eOWO",
  patrick: "ODq5zmih8GrVes37Dizd",
  harry: "SOYHLrjzK2X1ezoPC6cr",
  liam: "TX3LPaxmHKxFdv7VOQHJ",
  dorothy: "ThT5KcBeYPX3keUQqHPh",
  josh: "TxGEqnHWrfWFTfGW9XjX",
  arnold: "VR6AewLTigWG4xSOukaG",
  charlotte: "XB0fDUnXU5powFXDhCwa",
  matilda: "XrExE9yKIg1WjnnlVkGX",
  matthew: "Yko7PKs4biiYH3eDrLgN",
  james: "ZQe5CZNOzWyzPSCn5a3c",
  joseph: "Zlb1dXrM653N07WRdFW3",
  jeremy: "bVMeCyTHy58xNoL34h3p",
  michael: "flq6f7yk4E4fJM5XTYuZ",
  ethan: "g5CIjZEefAph4nQFvHAz",
  gigi: "jBpfuIE2acCO8z3wKNLl",
  freya: "jsCqWAovK2LkecY7zXl4",
  grace: "oWAxZDx7w5VEj9dCyTzz",
  daniel: "onwK4e9ZLuTAKqWW03F9",
  serena: "pMsXgVXv3BLzUgSXRplE",
  adam: "pNInz6obpgDQGcFmaJgB",
  nicole: "piTKgcLEGmPE4e6mEKli",
  jessie: "t0jbNlBVZ17f02VDIeMI",
  ryan: "wViXBPUzp2ZZixB1xQuM",
  sam: "yoZ06aMxZJJ28mfd3POQ",
  glinda: "z9fAnlkpzviPz146aGWa",
  giovanni: "zcAOhNBS3c14rBihAFp1",
  mimi: "zrHiDhphv9ZnVXBqCLjz",
};
